version: '3.9'
services:
  blogDb:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: db_blog
    networks:
      - backend
  blogDb-test:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: db_blog
    networks:
      - backend
  catblog-be:
    image: catblog-be
    ports:
      - 3000:8080
    environment:
      DATABASE_URL: "postgresql://postgres:123@localhost:5434/db_blog?schema=public"
      JWT_ACCESS_SECRET: 'slanáhoustička500ghladkémouky.250mlvlažnéhomléka.1/2kostkydroždí(cca20g)2lžícesádla.2lžičkysoli.špetkacukru.1vejcenapotřeníhrubásůl,kmín,mák,semínkanaposypání'
      JWT_ACCESS_EXP: "20m"
      JWT_REFRESH_SECRET: 'slanérohlíčky500ghladkámouka250mlmléko1kostkadroždí1lžičkasůl1,50dlrostlinnýolej1lžičkacukrkrupice'
      JWT_REFRESH_EXP: "999m"
    networks:
      - backend
networks:
  backend: