version: '3.9'
services:
  blogDb:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: db_blog
    networks:
      - backend
networks:
  backend: